app/blueprints/professor/__init__.py
from flask import Blueprint

# Create the Blueprint for professor
professor = Blueprint('professor', __name__, template_folder='templates')

# Import all routes from the routes directory
from .routes import home, add_student, edit_student, delete_student

app/blueprints/professor/routes/add_student.py
from flask import flash, redirect, request, url_for
from flask_login import current_user, login_required

from app.models.student import Student
from .. import professor
from app import db


@professor.route("/add_student", methods=["GET", "POST"])
@login_required
def add_student():
    if current_user.role != "professor":
        return redirect(url_for("auth.login"))

    if request.method == "POST":
        try:
            first_name = request.form.get("firstName")
            last_name = request.form.get("lastName")
            grade_1 = float(request.form.get("grade1"))
            grade_2 = float(request.form.get("grade2"))
            grade_3 = float(request.form.get("grade3"))

            # Validate grades
            if not all(0 <= grade <= 10 for grade in [grade_1, grade_2, grade_3]):
                raise ValueError("Grades must be between 0 and 10.")

            new_student = Student(
                first_name=first_name,
                last_name=last_name,
                grade_1=grade_1,
                grade_2=grade_2,
                grade_3=grade_3,
                professor_id=current_user.id
            )
            new_student.calculate_average()
            new_student.determine_result()

            db.session.add(new_student)
            db.session.commit()
            flash("Student added successfully!", category="success")
        except ValueError:
            db.session.rollback()
            flash("Please enter valid grades.", category="error")
        except Exception as e:
            db.session.rollback()
            flash(f"Error adding student: {e}", category="error")

    return redirect(url_for("professor.home"))

app/blueprints/professor/routes/delete_student.py
from flask import flash, redirect, url_for
from flask_login import login_required

from .. import professor
from app.models.student import Student
from app import db


@professor.route("/delete_student/<int:student_id>", methods=["GET", "POST"])
@login_required
def delete_student(student_id):
    try:
        student = Student.query.get_or_404(student_id)

        db.session.delete(student)
        db.session.commit()
        flash("Student successfully deleted!", category="success")
    except Exception as e:
        db.session.rollback()  # Reverte a transação para evitar inconsistências
        flash(f"An error occurred while deleting the student: {e}", category="error")

    return redirect(
        url_for("professor.home")
    )

app/blueprints/professor/routes/edit_student.py
from flask import flash, redirect, request, url_for
from flask_login import current_user, login_required

from app.models.student import Student
from .. import professor
from app import db


@professor.route("/edit_student/<int:student_id>", methods=["GET", "POST"])
@login_required
def edit_student(student_id):
    if current_user.role != "professor":
        return redirect(url_for("auth.login"))

    student = Student.query.filter_by(id=student_id).first_or_404()

    if request.method == "POST":
        try:
            student.first_name = request.form.get("firstName")
            student.last_name = request.form.get("lastName")
            student.grade_1 = float(request.form.get("grade1"))
            student.grade_2 = float(request.form.get("grade2"))
            student.grade_3 = float(request.form.get("grade3"))

            student.calculate_average()
            student.determine_result()

            db.session.commit()
            flash("Student updated successfully!", category="success")
        except ValueError:
            db.session.rollback()
            flash("Please enter valid grades.", category="error")
        except Exception as e:
            db.session.rollback()
            flash(f"Error updating student: {e}", category="error")

    return redirect(url_for("professor.home"))

app/blueprints/professor/routes/home.py
from flask import redirect, render_template, url_for
from flask_login import current_user, login_required

from app.models.student import Student
from .. import professor


@professor.route("/")
@login_required
def home():
    if current_user.role != "professor":
        return redirect(url_for("auth.login"))

    students = Student.query.all()
    return render_template("professor.html", user=current_user, students=students)

app/blueprints/professor/templates/modals/add_student.html
<!-- Modal para Adicionar Estudante -->
<div class="modal fade" id="addStudentModal" tabindex="-1" aria-labelledby="addStudentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <header class="modal-header">
                <h5 class="modal-title" id="addStudentModalLabel">Add Student</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </header>

            <form action="{{ url_for('professor.add_student') }}" method="post">
                <div class="modal-body">
                    <div class="mb-4">
                        <label for="firstName" class="form-label">First Name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" required>
                    </div>
                    <div class="mb-4">
                        <label for="lastName" class="form-label">Last Name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade1" class="form-label">Grade 1</label>
                        <input type="number" class="form-control" id="grade1" name="grade1" step="any" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade2" class="form-label">Grade 2</label>
                        <input type="number" class="form-control" id="grade2" name="grade2" step="any" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade3" class="form-label">Grade 3</label>
                        <input type="number" class="form-control" id="grade3" name="grade3" step="any" required>
                    </div>
                </div>
                <footer class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Add Student</button>
                </footer>
            </form>
        </div>
    </div>
</div>

app/blueprints/professor/templates/modals/delete_student.html
<!-- Delete Modal -->
<div class="modal fade" id="deleteStudentModal{{ student.id }}" tabindex="-1"
    aria-labelledby="deleteStudentModalLabel{{ student.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteStudentModalLabel{{ student.id }}">
                    Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-start">
                Are you sure you want to delete the student {{ student.first_name }} {{
                student.last_name }}?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="{{ url_for('professor.delete_student', student_id=student.id) }}"
                    class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

app/blueprints/professor/templates/modals/edit_student.html
<!-- Edit Modal -->
<div class="modal fade" id="editStudentModal{{ student.id }}" tabindex="-1"
    aria-labelledby="editStudentModalLabel{{ student.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <header class="modal-header">
                <h5 class="modal-title" id="editStudentModalLabel{{ student.id }}">
                    Edit Student
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </header>

            <form action="{{ url_for('professor.edit_student', student_id=student.id) }}" method="post">
                <div class="modal-body text-start">
                    <div class="mb-4">
                        <label for="firstName" class="form-label">First Name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName"
                            value="{{ student.first_name }}" required>
                    </div>
                    <div class="mb-4">
                        <label for="lastName" class="form-label">Last Name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName"
                            value="{{ student.last_name }}" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade1" class="form-label">Grade 1</label>
                        <input type="number" class="form-control" id="grade1" name="grade1"
                            value="{{ student.grade_1 }}" step="any" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade2" class="form-label">Grade 2</label>
                        <input type="number" class="form-control" id="grade2" name="grade2"
                            value="{{ student.grade_2 }}" step="any" required>
                    </div>
                    <div class="mb-4">
                        <label for="grade3" class="form-label">Grade 3</label>
                        <input type="number" class="form-control" id="grade3" name="grade3"
                            value="{{ student.grade_3 }}" step="any" required>
                    </div>
                </div>
                <footer class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </footer>
            </form>

        </div>
    </div>
</div>

app/blueprints/professor/templates/professor.html
{% extends "base.html" %}

<!-- Head -->
{% block title %} Home | GRADA {% endblock title %}

<!-- Body -->
{% block content %}

<div class="my-3 px-5 py-3 bg-body rounded shadow-sm">
    <div class="d-flex justify-content-between align-items-center my-2">
        <h2>Students</h2>
        <button class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#addStudentModal">
            <i class="bi bi-plus-lg"></i> Add Student
        </button>

        {% include "modals/add_student.html" %}
    </div>

    <!-- Table  -->
    <div class="card-body table-responsive table-scroll">
        <table class="table table-striped table-bordered table-hover align-middle">
            <thead>
                <tr class="table-dark">
                    <th scope="col" class="text-center">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col" class="text-end">Grade 1</th>
                    <th scope="col" class="text-end">Grade 2</th>
                    <th scope="col" class="text-end">Grade 3</th>
                    <th scope="col" class="text-end">Average</th>
                    <th scope="col" class="text-center">Result</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row" class="text-center">{{ student.id }}</th>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td class="text-end">{{ student.grade_1 }}</td>
                    <td class="text-end">{{ student.grade_2 }}</td>
                    <td class="text-end">{{ student.grade_3 }}</td>
                    <td class="text-end">{{ student.average }}</td>
                    {% if student.result == "Passed" %}
                    <td class="text-success text-center">
                        <i class="bi bi-check-square-fill"></i>
                    </td>
                    {% elif student.result == "Failed" %}
                    <td class="text-danger text-center">
                        <i class="bi bi-x-square-fill"></i>
                    </td>
                    {% endif %}

                    <td class="text-center">
                        <button class="btn btn-sm btn-outline-dark" data-bs-toggle="modal"
                            data-bs-target="#editStudentModal{{ student.id }}">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                            data-bs-target="#deleteStudentModal{{ student.id }}">
                            <i class="bi bi-trash3"></i>
                        </button>

                        {% include "modals/edit_student.html" %}
                        {% include "modals/delete_student.html" %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock content %}