app/blueprints/coordinator/__init__.py
from flask import Blueprint

# Create the Blueprint for coordinator
coordinator = Blueprint('coordinator', __name__, template_folder='templates')

# Import all routes from the routes directory
from .routes import home, edit_professor, delete_professor

app/blueprints/coordinator/routes/delete_professor.py
from flask import flash, redirect, url_for
from flask_login import login_required

from app.models.user import User
from .. import coordinator
from app import db


@coordinator.route("/delete_professor/<int:professor_id>", methods=["GET", "POST"])
@login_required
def delete_professor(professor_id):
    try:
        professor = User.query.get_or_404(professor_id)

        if professor.role != "professor":
            flash("You do not have permission to delete this user.", category="error")
        else:
            db.session.delete(professor)
            db.session.commit()
            flash("Professor deleted successfully!", category="success")
    except Exception as e:
        db.session.rollback()
        flash(f"An error occurred while deleting the professor: {e}", category="error")

    return redirect(
        url_for("coordinator.home")
    )

app/blueprints/coordinator/routes/edit_professor.py
from flask import flash, redirect, request, url_for
from flask_login import login_required

from app.models.user import User
from .. import coordinator
from app import db


@coordinator.route("/edit_professor/<int:professor_id>", methods=["GET", "POST"])
@login_required
def edit_professor(professor_id):
    professor = User.query.filter_by(id=professor_id, role="professor").first_or_404()

    if request.method == "POST":
        professor.first_name = request.form.get("firstName")
        professor.last_name = request.form.get("lastName")
        professor.email = request.form.get("email")
        
        try:
            db.session.commit()
            flash("Professor updated successfully!", category="success")
        except Exception as e:
            db.session.rollback()
            flash(f"Error updating professor: {e}", category="error")

    return redirect(url_for("coordinator.home"))

app/blueprints/coordinator/routes/home.py
from flask import render_template
from flask_login import current_user, login_required

from app.models.user import User
from .. import coordinator


@coordinator.route("/")
@login_required
def home():
    professors = User.query.filter_by(role="professor").all()

    return render_template("coordinator.html", user=current_user, professors=professors)

app/blueprints/coordinator/templates/coordinator.html
{% extends "base.html" %}

<!-- Head -->
{% block title %} Home | GRADA {% endblock title %}

<!-- Body -->
{% block content %}

<div class="my-3 px-5 py-3 bg-body rounded shadow-sm">
    <div class="d-flex justify-content-between align-items-center my-3">
        <h2>Professors</h2>
    </div>

    <!-- Table  -->
    <div class="card-body table-responsive table-scroll">
        <table class="table table-striped table-bordered table-hover align-middle text-center">
            <thead>
                <tr class="table-dark">
                    <th scope="col">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for professor in professors %}
                <tr>
                    <th scope="row">{{ professor.id }}</th>
                    <td>{{ professor.first_name }}</td>
                    <td>{{ professor.last_name }}</td>
                    <td>{{ professor.email }}</td>
                    <td>

                        <button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal"
                            data-bs-target="#editProfessorModal{{ professor.id }}">
                            <i class="bi bi-pencil-square"></i>
                        </button>

                        <button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                            data-bs-target="#deleteProfessorModal{{ professor.id }}">
                            <i class="bi bi-trash3"></i>
                        </button>

                        <!-- Edit Modal -->
                        <div class="modal fade" id="editProfessorModal{{ professor.id }}" tabindex="-1"
                            aria-labelledby="editProfessorModalLabel{{ professor.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <header class="modal-header">
                                        <h5 class="modal-title" id="editProfessorModalLabel{{ professor.id }}">Editar
                                            Professor</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </header>

                                    <form action="{{ url_for('coordinator.edit_professor', professor_id=professor.id) }}" method="post">
                                        <div class="modal-body text-start">
                                            <div class="mb-4">
                                                <label for="firstName" class="form-label">First Name</label>
                                                <input type="text" class="form-control" id="firstName" name="firstName"
                                                    value="{{ professor.first_name }}" required>
                                            </div>
                                            <div class="mb-4">
                                                <label for="lastName" class="form-label">Last Name</label>
                                                <input type="text" class="form-control" id="lastName" name="lastName"
                                                    value="{{ professor.last_name }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="email" class="form-label">Email</label>
                                                <input type="email" class="form-control" id="email" name="email"
                                                    value="{{ professor.email }}" required>
                                            </div>
                                        </div>
                                        <footer class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-bs-dismiss="modal">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save Changes</button>
                                        </footer>
                                    </form>

                                </div>
                            </div>
                        </div>

                        <!-- Delete Modal -->
                        <div class="modal fade" id="deleteProfessorModal{{ professor.id }}" tabindex="-1"
                            aria-labelledby="deleteProfessorModalLabel{{ professor.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteProfessorModalLabel{{ professor.id }}">
                                            Delete</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body text-start">
                                        Are you sure you want to delete the professor {{ professor.first_name }} {{
                                        professor.last_name }}?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Cancel</button>
                                        <a href="{{ url_for('coordinator.delete_professor', professor_id=professor.id) }}"
                                            class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
{% endblock content %}